### ISSUE TITLE
Automatic Update for planning

### ISSUE THREAD

**Issue by MyaMorocco** [khalid-elabbadi/Easyschool#34]
**EMERGENCY**
The problem now with this new hour (GMT+1) will be applicated for 2 mounths, and after 2 mounths it will recognize to GMT for schools, which means, now they are starting at 9am, and after 2 mounths they will start at 8am, which means the whole planning should be redone from ZERO. 
The idea is to make something automaticly that able to users change time and automaticly it will be applicated in the whole planning.

**Comment by khalid-elabbadi** [comment]
Fixed
