### ISSUE TITLE
Problem de calcul dans les rappels des impayés

### ISSUE THREAD

**Issue by MyaMorocco** [khalid-elabbadi/Easyschool#35]
When you click to have the list of  impaied students list's reminder, it add all students not one by one. 
here is some screens

![image](https://user-images.githubusercontent.com/42932849/48849237-3a1af780-eda6-11e8-8d3e-5f990148f2f2.png)

![image](https://user-images.githubusercontent.com/42932849/48849265-47d07d00-eda6-11e8-9453-c0496de7f226.png)
 **### here is the last page** 
![image](https://user-images.githubusercontent.com/42932849/48849281-4ef78b00-eda6-11e8-90e8-eed2718959ac.png)

**Comment by MyaMorocco** [comment]
The problem is stay appear!! Please recheck it!

the purpose of this report is to know how much is unpaid per student, not massive ones!!!

**Comment by MyaMorocco** [comment]
![image](https://user-images.githubusercontent.com/42932849/49829439-b9d92800-fd8e-11e8-9298-15f404eadbe1.png)

**Comment by MyaMorocco** [comment]
![image](https://user-images.githubusercontent.com/42932849/49829483-d5443300-fd8e-11e8-9bdb-52373b7dab13.png)

**Comment by khalid-elabbadi** [comment]
I fixed this issue, please redo your Testing case

**Do not forget to close this issue if test is OK**

**Comment by MyaMorocco** [comment]
TEST OK
