### ISSUE TITLE
Bug in Assign function to agent

### ISSUE THREAD

**Issue by MyaMorocco** [khalid-elabbadi/Easyschool#45]
![image](https://user-images.githubusercontent.com/42932849/49341860-affb4a80-f653-11e8-986a-a1affee9d84c.png)

However the coloumn is already there!

![image](https://user-images.githubusercontent.com/42932849/49341875-d0c3a000-f653-11e8-9631-541bcb12fc9b.png)

**Comment by khalid-elabbadi** [comment]
Fixed
