### ISSUE TITLE
Civilité & account user BUG

### ISSUE THREAD

**Issue by MyaMorocco** [khalid-elabbadi/Easyschool#47]
When you add a new teacher and you notice that she's a "Madame" or "Mademoiselle" and go back to check on her card it appears "Monsieur" on the civility it should appear Madame or Mademoiselle.
Besides it takes the first user account on the top , for example this teacher is "Madame" and doesn't have any account , it added automaticly every single time you open the window card! 

![image](https://user-images.githubusercontent.com/42932849/49380582-4c842200-f712-11e8-939b-d9340855b5b8.png)

**Comment by khalid-elabbadi** [comment]
Fixed
