### ISSUE TITLE
Changement de date des services payants

### ISSUE THREAD

**Issue by MyaMorocco** [khalid-elabbadi/Easyschool#48]
Par exemple un étudiant payait la "Cantine garde" pendant 3 mois, ensuite, les parents décident d'arrêter pendant le mois courant, quand tu rentres pour changer les dates début et fin du service en question, le système ne prend pas en considération cette date et affiche dans la zone des impayés que le mois en cours n'est pas encore payé "Cantine garde". 

![image](https://user-images.githubusercontent.com/42932849/49442062-a0e9d900-f7c8-11e8-88ea-fc79306a499c.png)

![image](https://user-images.githubusercontent.com/42932849/49442077-ab0bd780-f7c8-11e8-8338-ece6d7d66853.png)

**Comment by MyaMorocco** [comment]
Database Jenine

**Comment by khalid-elabbadi** [comment]
I fixed this issue, please redo your Testing case

**Do not forget to close this issue if test is OK**

**Comment by MyaMorocco** [comment]
Tested and approved! Good job
