### ISSUE TITLE
Durée d'absence dans 15min 

### ISSUE THREAD

**Issue by MyaMorocco** [khalid-elabbadi/Easyschool#50]
Dans la saisie des absences des teachers, il y a la durée qui est fixée à 15min, sans avoir la possibilité de la modifier. il serait mieux d'ajouter la durée d'absence (nouveau champs) et pour les teachers et pour les students! 

![image](https://user-images.githubusercontent.com/42932849/49950986-37b94280-fef9-11e8-83c6-f6867cb7dd9f.png)

**Comment by khalid-elabbadi** [comment]
Still have this issue after v7.25 ?

**Comment by MyaMorocco** [comment]
It's OK
